export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const TOGGLE_FORM = 'TOGGLE_FORM'
export const OPEN_ITEM_MODAL = 'OPEN_ITEM_MODAL'
export const CLOSE_ITEM_MODAL = 'CLOSE_ITEM_MODAL'
export const LOGOUT = 'LOGOUT'
export const WINDOW_RESIZE = 'WINDOW_RESIZE'
export const NO_HAMBURGER = 'NO_HAMBURGER'
export const GET_HAMBURGER = 'GET_HAMBURGER'
export const CLOSE_MENU = 'CLOSE_MENU'
export const OPEN_MENU = 'OPEN_MENU'
export const GET_USER = 'GET_USER'
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const GET_ITEMS = 'GET_ITEMS'
export const GET_ITEM = 'GET_ITEM'
export const UPLOAD_PHOTO = 'UPLOAD_PHOTO'

